server:
  port: 9096


spring:
  # jconsole admin
  application:
    name: "greetings"
    admin:
      enabled: true
  # Live Reload
  devtools:
    livereload:
      enabled: true
  # Log Color
  output:
    ansi:
      enabled: always
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    healthcheck:
      enabled: true