server:
  port: 9092

# 로깅
logging:
  level:
    root: info
    org.springframework.boot.web: info

spring:
  # jconsole admin
  application:
    admin:
      enabled: true
  # Live Reload
  devtools:
    livereload:
      enabled: true
  # Log Color
  output:
    ansi:
      enabled: always

---

spring:
  profiles:
    active: "dev"
service:
  message :
    text : "hello"
---

spring:
  profiles: "dev"
service:
  message:
    type : "simple"
    text : "hi"
---

spring:
  profiles: "prod"
service:
  message:
    type: "advance"
    text: "welcome"
